name: Lint
on: pull_request

jobs:
  text:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "15"
      - name: Check
        uses: tsuyoshicho/action-textlint@v3
        with:
          textlint_flags: "**/*.md"
          level: warning

  markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: markdownlint
        uses: reviewdog/action-markdownlint@v0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
